AWSTemplateFormatVersion: 2010-09-09
Description: API Gateway and Lambda function
Parameters: 
  env:
    Description: Environment varaible
    Type: String
    Default: staging    
    
Resources:
  CreateProjectFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: my-gsp-cicd-test
        S3Key: gsp-sneha-lambda-zip.zip
      Description: Testing deployment
      FunctionName: mylambdaFunctionName-!Ref env
      Handler: CreateProject.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::827508809103:role/LambdaServiceRole
      Runtime: python3.6
      Timeout: 10
