AWSTemplateFormatVersion: 2010-09-09
Description: API Gateway and Lambda function
Parameters: 
  env:
    Description: Environment varaible
    Type: String
    Default: staging    
    
Resources:
  CreateProjectFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          def handler(event, context):
            print('hello from lambda')
      Description: Testing deployment
      FunctionName: mylambdaFunctionName-!Ref env
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::827508809103:role/LambdaServiceRole
      Runtime: python3.6
      Timeout: 10
