name: Infrastructure deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main  ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-1

    steps:
    - uses: actions/checkout@v2.1.0
    - run: |
        output=$(python a.py)
        output="${output//'%'/'%25'}"
        echo "::set-output name=changelog::$output"
      id: step1
      
    - name: Print changelog
      run: echo "${{ steps.step1.outputs.changelog }}"
      
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Get lambda function name
      id: lambda-function-name
      run: |
          if  ${{ steps.extract_branch.outputs.branch == 'main' }}; then
            echo "::set-output name=function-name::gsp-create-project"
          else
            echo "::set-output name=function-name::gsp-create-project-${{steps.extract_branch.outputs.branch}}"
          fi
            echo "finish"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA4BK26LWH5YPUBS5S
        aws-secret-access-key: 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
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Now Check if AWS Lambda Function is present
      id: get-function
      run: |
          cmd="aws lambda get-function --function-name ${{steps.lambda-function-name.outputs.function-name}}"
          $cmd
          ## get status ##
          status=$?
          [ $status -eq 0 ] && echo " command was successful" || echo " failed"

    - name: Now If present, update lambda
      run: |
        if  ${{ steps.get-function.outputs.error-code == '0'}} ; then
          echo "Lambda is present"
        else
          echo "Please create lambda function."
        fi
          echo "finish"
