name: Infrastructure deployment

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-1

    steps:


      - name: checkout
        uses: actions/checkout@v2
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4BK26LWH5YPUBS5S
          aws-secret-access-key: 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
          aws-region: us-west-1

      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          echo "Environment name: ${GITHUB_REF##*/}"

          echo "Environment name: ${{ if eq(${GITHUB_REF##*/} , 'main') }}: 'itsmain'"
          echo "::set-output name=environment:: ${GITHUB_REF##*/}"

      - name: Deploy CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ steps.env-name.outputs.environment }}-core
          template: my-cft.yaml
          parameter-overrides: "env=${{ steps.env-name.outputs.environment }}"
          no-fail-on-empty-changeset: "1"
