name: Infrastructure deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-1

    steps:


      - name: checkout
        uses: actions/checkout@v2
        
      - name: Branch name
        run: |
          echo running on branch ${GITHUB_REF##*/}
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4BK26LWH5YPUBS5S
          aws-secret-access-key: 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
          aws-region: us-west-1
          
      - name: Get branch name
        id: branch-name
        run: |
            echo "::set-output name=br_name:: ${GITHUB_REF##*/}" 
            
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'        
        run: echo "This step will be skipped on Monday and Wednesday".
        
      - name: Every time
        run: echo "This step will always run"
            
            
        
          

