name: Infrastructure deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-1

    steps:


      - name: checkout
        uses: actions/checkout@v2
        
      - name: Branch name
        run: |
          echo running on branch ${GITHUB_REF##*/}
          echo running on branch GITHUB_REF
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4BK26LWH5YPUBS5S
          aws-secret-access-key: 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
          aws-region: us-west-1

      - name: Get Environment name
        id: env-name
        env:
          IS_PROD: ${GITHUB_REF##*/} == 'main'       
        run: |
          if ${IS_PROD}; then
            echo "::set-output name=environment:: ''" 
          else
            echo "::set-output name=environment:: ${GITHUB_REF##*/}" 
          fi
          echo "environment" 
          
      - name: print details   
        run: |
          echo "environment is ${{ steps.env-name.outputs.environment }}"           
