name: Infrastructure deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-1

    steps:


      - name: checkout
        uses: actions/checkout@v2
        
          
      - name: Get branch name
        id: branch-name
        run: |
            echo "::set-output name=br_name:: ${GITHUB_REF##*/}"       
            
      - name: Get Environment name
        id: env-name
        run: |
            echo "is main ${{ steps.branch-name.outputs.br_name == "main" }} "
            
            
        
          

