name: Infrastructure deployment

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-1

    steps:


      - name: checkout
        uses: actions/checkout@v2
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4BK26LWH5YPUBS5S
          aws-secret-access-key: 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
          aws-region: us-west-2

      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          ENVIRONMENT=`echo $REPO | tr "/" "-"`
          echo "Environment name: $ENVIRONMENT"
          echo "::set-output name=environment::$ENVIRONMENT"
        
      - name: Deploy CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dev-core
          template: my-cft.yaml
          parameter-overrides: "env=main"
          no-fail-on-empty-changeset: "1"
